timestamp:
  key: [time, ts]
  visible: true
  colors: [32,12,34]
  format: "02/01/2006 15:04:05"

logger:
  key: logger
  visible: true
  padding: 0

caller:
  key: caller
  visible: false
  padding: 0

level:
  key: [level, lvl]
  visible: true
  padding: 5
  colors:
    debug:
    info:
    warn:
    error:
    fatal:

message:
  key: msg
  padding: 0